apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcp-veo
  name: mcp-veo
  namespace: acedatacloud
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: mcp-veo
