// Auto-generated by scripts/build_vscode_extensions.py — DO NOT EDIT BY HAND.
//
// Registers the hosted Ace Data Cloud "veo" MCP server with VS Code
// via the stable `vscode.lm.registerMcpServerDefinitionProvider` API. The
// Bearer API key is read from (in order):
//   1. process.env.ACEDATACLOUD_API_TOKEN
//   2. VS Code SecretStorage (key "veo.apiToken")
//   3. An interactive showInputBox prompt on first use
//
// Two commands are exposed for managing the API key from the command palette:
//   - acedatacloud.veo.setApiToken
//   - acedatacloud.veo.clearApiToken

const vscode = require("vscode");

const PROVIDER_ID = "acedatacloud.veo";
const SERVER_LABEL = "Veo MCP";
const SERVER_URL = "https://veo.mcp.acedata.cloud/mcp";
const SET_TOKEN_CMD = "acedatacloud.veo.setApiToken";
const CLEAR_TOKEN_CMD = "acedatacloud.veo.clearApiToken";
// Per-extension SecretStorage namespace; we keep one key per service so
// rotating one API key doesn't affect siblings.
const SECRET_KEY = "veo.apiToken";
const SIGNUP_URL = "https://platform.acedata.cloud";

async function readToken(context) {
  const env = process.env.ACEDATACLOUD_API_TOKEN;
  if (env && env.trim()) return env.trim();
  const stored = await context.secrets.get(SECRET_KEY);
  return stored ? stored.trim() : undefined;
}

async function promptForToken(context) {
  const token = await vscode.window.showInputBox({
    title: `${SERVER_LABEL} — Ace Data Cloud API key`,
        prompt: `Paste an API key from ${SIGNUP_URL}/console/applications (Applications -> API Key). Stored in the OS keychain.`,
        placeHolder: "API key from /console/applications",
    password: true,
    ignoreFocusOut: true,
  });
  if (!token) return undefined;
  const trimmed = token.trim();
  if (!trimmed) return undefined;
  await context.secrets.store(SECRET_KEY, trimmed);
  return trimmed;
}

function activate(context) {
  const onDidChange = new vscode.EventEmitter();

  context.subscriptions.push(
    onDidChange,
    vscode.commands.registerCommand(SET_TOKEN_CMD, async () => {
      const t = await promptForToken(context);
      if (t) {
        vscode.window.showInformationMessage(`${SERVER_LABEL}: API key saved.`);
        onDidChange.fire();
      }
    }),
    vscode.commands.registerCommand(CLEAR_TOKEN_CMD, async () => {
      await context.secrets.delete(SECRET_KEY);
    vscode.window.showInformationMessage(`${SERVER_LABEL}: API key cleared.`);
      onDidChange.fire();
    }),
    context.secrets.onDidChange((e) => {
      if (e.key === SECRET_KEY) onDidChange.fire();
    }),
    vscode.lm.registerMcpServerDefinitionProvider(PROVIDER_ID, {
      onDidChangeMcpServerDefinitions: onDidChange.event,
      provideMcpServerDefinitions: () => [
        new vscode.McpHttpServerDefinition(SERVER_LABEL, vscode.Uri.parse(SERVER_URL)),
      ],
      resolveMcpServerDefinition: async (server) => {
        let token = await readToken(context);
        if (!token) token = await promptForToken(context);
        if (!token) {
          throw new Error(
                        `${SERVER_LABEL} needs an Ace Data Cloud API key. ` +
                            `Run "${SERVER_LABEL}: Set Ace Data Cloud API Key" from the command palette.`
          );
        }
        return new vscode.McpHttpServerDefinition(server.label, server.uri, {
          Authorization: `Bearer ${token}`,
        });
      },
    })
  );
}

function deactivate() {}

module.exports = { activate, deactivate };
